spring:
  data:
    cassandra: # Cassandra properties
      contact-points: localhost
      port          : 9042
      keyspace-name : user
      username      : ''
      password      : ''
      ssl           : false
      ttl           : 345600
      local-datacenter : datacenter1